services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - '5432:5432'
  marketplace:
    build:
      dockerfile: ./.Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - .\:/app/
    depends_on:
     - postgres
  redis:
    image: redis
    ports:
      - '6379:6379'